services:
    offwhite.reviewGenerator:
        class:      Offwhite\RaviewBundle\Services\reviewGenerator
        arguments: [%reviewGenerator.componentPath%]
    offwhite.tmdb:
        class:      Offwhite\RaviewBundle\Services\Tmdb
        arguments: [@doctrine.orm.entity_manager, %tmdb.api_key%, @offwhite.reviewGenerator]
